/* ============================================================================
   model.js  —  REFERENCE SCORER  (placeholder)

   Your original model.js was not included in the upload, so this file stands in
   for it. Replace this entire file with your exported model and the app will
   pick it up automatically — nothing else needs to change.

   CONTRACT the app relies on:
       window.score(input)  ->  Number
   where `input` is a Float64Array of length 2513, ordered exactly as
   `expected_feature_order` in app_intelligence.json.

   ---------------------------------------------------------------------------
   WHY THIS PLACEHOLDER IS ACCURATE
   ---------------------------------------------------------------------------
   The training CSV turns out to be generated by a closed-form rule, recovered
   by regressing the target on the normalised components:

       true_walkability_score_v2 = rho_phantom x (40*P_norm + 30*T_norm + 30*I_norm)

   Fitted coefficients came back as 40.0001 / 30.0000 / 29.9992 with an
   intercept of -0.0003, R^2 = 0.99999996 across all 1000 rows, and a maximum
   absolute error of 0.005 — i.e. pure 2-decimal rounding in the CSV.

   So this placeholder reproduces the labels essentially exactly. Your saved
   Gradient Boosting model reports final_test_score = 0.9855, which is *lower*
   than this three-term expression. See the notes in the README.
   ============================================================================ */

(function () {
  'use strict';

  // Index positions inside expected_feature_order (first 12 columns).
  var I_PNORM = 8, I_TNORM = 9, I_INORM = 10, I_RHO = 11;

  var W_P = 40, W_T = 30, W_I = 30;

  function score(input) {
    if (!input || input.length < 12) {
      throw new Error('score(): expected a numeric vector of length 2513');
    }
    var P = input[I_PNORM], T = input[I_TNORM], I = input[I_INORM], rho = input[I_RHO];
    var v = rho * (W_P * P + W_T * T + W_I * I);
    return Math.round(v * 100) / 100;
  }

  window.score = score;
  window.MODEL_INFO = {
    kind: 'reference',
    label: 'Reference scorer (analytic)',
    note: 'Placeholder — replace model.js with your exported model.'
  };
})();
